import AppIntents

@available(*, deprecated, message: "This action was moved to a separate app called “AI Actions” by the same author. It's a drop-in replacement.")
struct AskChatGPT: AppIntent {
	static let title: LocalizedStringResource = "Ask ChatGPT"

	static let description = IntentDescription(
"""
DEPRECATED. WILL BE REMOVED SOON.
""",
		categoryName: "AI"
	)

	@Parameter(title: "Prompt")
	var prompt: String

	@Parameter(title: "Model", default: .gpt3_5)
	var model: Model_AppEnum

	@Parameter(
		title: "Max Tokens",
		description: "The maximum number of tokens allowed for the generated answer."
	)
	var maxTokens: Int?

	@Parameter(
		title: "Temperature",
		description: "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or “topProbabilityMass” but not both. Default: 1",
		default: 1,
		// We don't use slider as it currently does not show the active value and it also does not respect the default value. (macOS 14)
//		controlStyle: .slider,
		inclusiveRange: (0, 2)
	)
	var temperature: Double

	@Parameter(
		title: "Top Probability Mass (top_p)",
		description: "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or “temperature” but not both. Default: 1",
		default: 1
	)
	var topProbabilityMass: Double

	@Parameter(
		title: "Presence Penalty",
		description: "Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics. Default: 0",
		default: 0,
//		controlStyle: .slider,
		inclusiveRange: (-2, 2)
	)
	var presencePenalty: Double

	@Parameter(
		title: "Frequency Penalty",
		description: "Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim. Default: 0",
		default: 0,
//		controlStyle: .slider,
		inclusiveRange: (-2, 2)
	)
	var frequencyPenalty: Double

	@Parameter(
		title: "Logit Bias",
		description:
"""
Modify the likelihood of specified tokens appearing in the completion.

Accepts a dictionary that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. Use “Number” as the value type. You can use this tokenizer tool to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.

As an example, you can pass {"50256": -100} to prevent the <|endoftext|> token from being generated.
""",
		inputOptions: String.IntentInputOptions(
			capitalizationType: .none,
			autocorrect: false,
			smartQuotes: false,
			smartDashes: false
		)
//		supportedTypeIdentifiers: ["public.json"]
	)
	// We are not using IntentFile as it cannot use a variable on macOS. (macOS 14)
//	var logitBias: IntentFile
	var logitBias: String?

	static var parameterSummary: some ParameterSummary {
		Summary("Ask ChatGPT \(\.$prompt)") {
			\.$model
			\.$maxTokens
			\.$temperature
			\.$topProbabilityMass
			\.$presencePenalty
			\.$frequencyPenalty
			\.$logitBias
		}
	}

	func perform() async throws -> some IntentResult & ReturnsValue<String> {
		#if os(macOS)
		"https://sindresorhus.com/ai-actions".openUrl()
		#endif

		return .result(value: "PLEASE READ: This action was moved to a separate app called “AI Actions” by the same author. It's a drop-in replacement. The action in that app is called “Ask AI”. https://sindresorhus.com/ai-actions")
	}
}

enum Model_AppEnum: String, AppEnum {
	case gpt3_5
	case gpt4

	static let typeDisplayRepresentation: TypeDisplayRepresentation = "Model"

	static let caseDisplayRepresentations: [Self: DisplayRepresentation] = [
		.gpt3_5: "GPT-3.5",
		.gpt4: "GPT-4 (Requires special access!)"
	]
}
